# Generated by Django 5.2.5 on 2025-09-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='estilo',
            field=models.CharField(default='natureza', help_text='Ex: natureza, cidade, praia, etc.', max_length=50),
        ),
    ]
