# Generated by Django 5.2.5 on 2025-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_remove_foto_estilo_alter_foto_continente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='continente',
            field=models.CharField(choices=[('america-do-sul', 'América do Sul'), ('america-do-norte', 'América do Norte'), ('europa', 'Europa'), ('asia', 'Ásia'), ('africa', 'África'), ('oceania', 'Oceania'), ('antartida', 'Antártida')], default='america-do-sul', max_length=30),
        ),
    ]
