# Generated by Django 5.2.5 on 2025-09-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_foto_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='continente',
            field=models.CharField(default='América do Sul', help_text='Ex: América do Sul, Europa, Ásia, África, Oceania, América do Norte, Antártida', max_length=30),
        ),
    ]
