# Generated by Django 5.2.5 on 2025-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_foto_continente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='estilo',
        ),
        migrations.AlterField(
            model_name='foto',
            name='continente',
            field=models.CharField(choices=[('América do Sul', 'América do Sul'), ('América do Norte', 'América do Norte'), ('Europa', 'Europa'), ('Ásia', 'Ásia'), ('África', 'África'), ('Oceania', 'Oceania'), ('Antártida', 'Antártida')], default='América do Sul', max_length=30),
        ),
    ]
