# Generated by Django 5.2.5 on 2025-09-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0005_alter_foto_continente'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Marque para que esta foto possa aparecer na página inicial.'),
        ),
    ]
