# Generated by Django 5.2.5 on 2025-09-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0006_foto_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='estilo',
            field=models.CharField(choices=[('paisagem', 'Paisagem'), ('retratos', 'Retratos'), ('urbano', 'Urbano'), ('natureza', 'Natureza'), ('cultural', 'Cultural'), ('aventura', 'Aventura')], default='paisagem', max_length=30),
        ),
    ]
